# Generated by Django 4.2.1 on 2023-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.CharField(max_length=1000)),
                ("mes", models.CharField(max_length=1000)),
                ("indice", models.CharField(max_length=50)),
                ("variacao_mensal", models.CharField(max_length=1000)),
                ("variacao_12_meses", models.CharField(max_length=1000)),
                ("variacao_acumulada_ano", models.CharField(max_length=1000)),
                ("indice_fechamento_mensal", models.CharField(max_length=1000)),
            ],
        ),
    ]
