# Generated by Django 4.2.1 on 2023-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_indice_indice_fechamento_mensal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PIB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.CharField(default=0, max_length=100)),
                ("id_uf", models.CharField(default=0, max_length=100)),
                ("sigla_uf", models.CharField(default=0, max_length=100)),
                ("pib", models.CharField(default=0, max_length=100)),
                ("impostos_liquidos", models.CharField(default=0, max_length=100)),
                ("va", models.CharField(default=0, max_length=100)),
                ("va_agropecuaria", models.CharField(default=0, max_length=100)),
                ("va_industria", models.CharField(default=0, max_length=100)),
                ("va_servicos", models.CharField(default=0, max_length=100)),
                ("va_adespss", models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
